# Railway configuration for BadgerCite server deployment
[build]
  builder = "RAILPACK"

[deploy]
  runtime = "V1"
  startCommand = "node server/index.js"
  healthcheckPath = "/health"
  healthcheckTimeout = 300

[build.environment]
  NODE_ENV = "production"