name = "badgercite"
main = "client/build"
compatibility_date = "2025-09-26"

[build]
command = "cd client && npm ci --omit=dev && npm run build"
cwd = "/"

[build.environment_variables]
NODE_ENV = "production"
REACT_APP_API_URL = "https://gzma5olj.up.railway.app"

pages_build_output_dir = "client/build"